ePortfolio 2.3/src/objects/LP_Template_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Header_Logo__c</fullName>
        <description>id of document that contains image for learner profile logo in header</description>
        <inlineHelpText>id of document that contains image for learner profile logo in header</inlineHelpText>
        <label>Header Logo</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>LP Template Settings</label>
</CustomObject>

ePortfolio 2.3/src/objects/Menu__c.object
<CustomObject>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <label>Menu</label>
    <nameField>
        <label>Menu Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Menu</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ePortfolio 2.3/src/classes/LPHeaderController.cls
public with sharing class LPHeaderController {
  List<Menu__c> menuItems;
  /* grabs list of records in Menu__c for display in header */
  public List<Menu__c> getMenuItems() {
    return [SELECT Id, Name, URL__c, Sort_Order__c FROM Menu__c ORDER BY Sort_Order__c]; 
  }
  /* Logo for display in internal header */
  public String getLogoUrl() {
    LP_Template_Settings__c lpts = LP_Template_Settings__c.getOrgDefaults();
    return (lpts == NULL || String.isBlank(lpts.Header_Logo__c)) ? NULL : lpts.Header_Logo__c;
  }
}